### ISSUE TITLE
fix camera data

### ISSUE THREAD

**Issue by yanmingsohu** [OpenBiohazard2/OpenBiohazard2#2]
```
type RIDHeader struct {
	Flag        uint16
	FOV         uint8  //!!!!! & 0x7F
	Unknown     uint8
	CameraFromX int32
	CameraFromY int32
	CameraFromZ int32
	CameraToX   int32
	CameraToY   int32
	CameraToZ   int32
	MaskOffset  uint32
}
```

**Comment by samuelyuan** [comment]
The reason I didn't set byte+02 to FOV and byte+03 to Unknown is because the game engine only uses byte+03 for the camera FOV calculations. If you were to change byte+02 to a different value and load the file in the original engine, the FOV would still stay the same. However if you change byte+03 to a different value, the camera FOV will be completely different.

**Comment by yanmingsohu** [comment]
Maybe the original engine used some kind of switch to determine fov for efficiency?

**Comment by yanmingsohu** [comment]
I tested multiple scenarios with byte + 02 (not primitive engine),
The characters and the background can perfectly match, especially the scenes inside the police station have strict requirements on fov.
It looks like the problem is solved, as long as fov is correct.
